<?php

namespace Whoo\Config;

class Controller {
    const REQUIRED = [
        // this is example to test
        'Example'=>[
            'strValue'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>10,
                    'max'=>50
                ]
            ],
            'numValue'=>[
                'type'=>'num',
                'limits'=>[
                    'min'=>1,
                    'max'=>10
                ]
            ],
            'arrValue'=>[
                'type'=>'arr',
                'limits'=>[
                    'min'=>2,
                    'max'=>5
                ]
            ],
            'emailValue'=>[
                'type'=>'email',
                'limits'=>[
                    'min'=>1,
                    'max'=>255
                ]
            ],
            'boolValue'=>[
                'type'=>'bool'
            ]
        ],
        // ^ this is exampe to test
        'SignUp'=>[
            'email'=>[
                'type'=>'email',
                'limits'=>[
                    'min'=>1,
                    'max'=>255
                ]
            ],
            'password'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>8,
                    'max'=>50
                ]
            ]
        ],
        'SignIn'=>[
            'who'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>0,
                    'max'=>50
                ]
            ],
            'email'=>[
                'type'=>'email',
                'limits'=>[
                    'min'=>1,
                    'max'=>255
                ]
            ],
            'password'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>8,
                    'max'=>50
                ]
            ]
        ],
        'SignInByUsername'=>[
            'who'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>0,
                    'max'=>50
                ]
            ],
            'username'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>1,
                    'max'=>40
                ]
            ],
            'password'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>8,
                    'max'=>50
                ]
            ]
        ],
        'SetUsername'=>[
            'temporaryToken'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>50,
                    'max'=>50
                ]
            ],
            'username'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>1,
                    'max'=>40
                ]
            ]
        ],
        'SetAuthCodeForEmailVerification'=>[
            'email'=>[
                'type'=>'email',
                'limits'=>[
                    'min'=>1,
                    'max'=>255
                ]
            ]
        ],
        'VerifyEmail'=>[
            'email'=>[
                'type'=>'email',
                'limits'=>[
                    'min'=>1,
                    'max'=>255
                ]
            ],
            'code'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>1,
                    'max'=>10
                ]
            ]
        ],
        'SignOut'=>[
            'jwt'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>1,
                    'max'=>1000
                ]
            ]
        ],
        'SignInByProvider'=>[
            'who'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>0,
                    'max'=>50
                ]
            ],
            'email'=>[
                'type'=>'email',
                'limits'=>[
                    'min'=>1,
                    'max'=>255
                ]
            ],
            'provider'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>1,
                    'max'=>255
                ]
            ],
            'providerId'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>1,
                    'max'=>255
                ]
            ],
        ],
        'SetAuthCodeToResetPassword'=>[
            'email'=>[
                'type'=>'email',
                'limits'=>[
                    'min'=>1,
                    'max'=>255
                ]
            ]
        ],
        'ResetPassword'=>[
            'newPassword'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>8,
                    'max'=>50
                ]
            ],
            'code'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>1,
                    'max'=>10
                ]
            ]
        ],
        'ChangeEmail'=>[
            'jwt'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>1,
                    'max'=>1000
                ]
            ],
            'newEmail'=>[
                'type'=>'email',
                'limits'=>[
                    'min'=>1,
                    'max'=>255
                ]
            ],
            'password'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>8,
                    'max'=>50
                ]
            ],
        ],
        'ChangeUsername'=> [
            'jwt'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>1,
                    'max'=>1000
                ]
            ],
            'newUsername'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>1,
                    'max'=>40
                ]
            ],
        ],
        'ChangePassword'=>[
            'jwt'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>1,
                    'max'=>1000
                ]
            ],
            'password'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>8,
                    'max'=>50
                ]
            ],
            'newPassword'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>8,
                    'max'=>50
                ]
            ]
        ],
        'SetAuthCodeForManage2FA'=>[
            'jwt'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>1,
                    'max'=>1000
                ]
            ]
        ],
        'Manage2FA'=>[
            'jwt'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>1,
                    'max'=>1000
                ]
            ],
            'code'=>[
                'type'=>'str',
                'limits'=>[
                    'min'=>1,
                    'max'=>10
                ]
            ],
            'open'=>[
                'type'=>'bool'
            ]
        ]
    ];
}
